name: Setup script test

on:
  workflow_dispatch:

jobs:
  setup:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        node: [14]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - name: Update npm
        run: npm i -g npm@7.3.0
      - run: npm ci --production
      - run: npm run bootstrap -- -- --production --scope @amplication/server --scope @amplication/client --include-dependencies
